BankingMVCWithUnitTesting/Controllers/AccountBankController.cs
using BankingMVCWithUnitTesting.Models;
using BankingMVCWithUnitTesting.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BankingMVCWithUnitTesting.Controllers
{
    public class AccountBankController : Controller
    {
        AccountBankRepository ab = new AccountBankRepository();
        BanksRepository br = new BanksRepository();
        AccountRepository ar = new AccountRepository();

        // GET: AccountBank
        public ActionResult Index()
        {
            return View(br.GetAllBanks().ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bank bank = br.GetBankByID(id);
            if (bank == null)
            {
                return HttpNotFound();
            }
            return View(bank);
        }

        public ActionResult ViewAccounts(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bank bank = br.GetBankByID(id);
            IEnumerable<Account> acc = bank.Accounts;
            if (bank == null)
            {
                return HttpNotFound();
            }
            return View(acc);
        }

        public ActionResult ViewTransHistory(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = ar.GetById(id);
            IEnumerable<Trans> trans = account.Transactions;
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(trans);
        }

        public ActionResult Deposit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = ar.GetById(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deposit(Account account, double amount)
        {
            if (ModelState.IsValid)
            {
                ab.Deposit(account, amount);
                return RedirectToAction("Index");
            }
            return View(account);
        }
    }
}

BankingMVCWithUnitTesting/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BankingMVCWithUnitTesting.DataAccess;
using BankingMVCWithUnitTesting.Models;
using BankingMVCWithUnitTesting.Repositories;

namespace BankingMVCWithUnitTesting.Controllers
{
    public class AccountsController : Controller
    {
        private AccountRepository db = new AccountRepository();

        // GET: Accounts
        public ActionResult Index()
        {
            return View(db.GetAllAccounts().ToList());
        }

        // GET: Accounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.GetById(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // GET: Accounts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AccountHolderFName,AccountHolderLName,SSN,Email,PhoneNumber,Address")] Account account)
        {
            if (ModelState.IsValid)
            {
                db.Add(account);
                return RedirectToAction("Index");
            }

            return View(account);
        }

        // GET: Accounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.GetById(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AccountHolderFName,AccountHolderLName,SSN,Email,PhoneNumber,Address")] Account account)
        {
            if (ModelState.IsValid)
            {
                db.Edit(account);
                return RedirectToAction("Index");
            }
            return View(account);
        }

        // GET: Accounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.GetById(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Account account = db.GetById(id);
            db.Delete(account);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BankingMVCWithUnitTesting/Views/AccountBank/Deposit.cshtml
@model BankingMVCWithUnitTesting.Models.Account

@{
    ViewBag.Title = "Deposit";
}

<h2>Deposit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Account</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        
        @using (Html.BeginForm("Deposit", "AccountBank", FormMethod.Post))
        {
            <input type="number" name="amount" id="amount" placeholder="Enter a number..." />

            <input type="submit" value="Deposit" />
        }

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankingMVCWithUnitTesting/Views/AccountBank/Details.cshtml
@model BankingMVCWithUnitTesting.Models.Bank

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Bank</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BankName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankCapital)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankCapital)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("View Accounts", "ViewAccounts", new { id = Model.ID}) |
    @Html.ActionLink("Back to List", "Index")
</p>

BankingMVCWithUnitTesting/Views/AccountBank/Index.cshtml
@model IEnumerable<BankingMVCWithUnitTesting.Models.Bank>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BankName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankCapital)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BankName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BankCapital)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

BankingMVCWithUnitTesting/Views/AccountBank/ViewAccounts.cshtml
@model IEnumerable<BankingMVCWithUnitTesting.Models.Account>

@{
    ViewBag.Title = "ViewAccounts";
}

<h2>ViewAccounts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Bank.BankName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountHolderFName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountHolderLName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SSN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Bank.BankName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountHolderFName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountHolderLName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SSN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", "Accounts", new { id=item.ID }, null) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

BankingMVCWithUnitTesting/Views/AccountBank/ViewTransHistory.cshtml
@model IEnumerable<BankingMVCWithUnitTesting.Models.Trans>

@{
    ViewBag.Title = "ViewTransHistory";
}

<h2>ViewTransHistory</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>